CREATE TABLE [core].[Config]
(
  [ConfigId] INT NOT NULL IDENTITY (1, 1)
, [ConfigName] VARCHAR(28) NULL
, [ConfigValue] VARCHAR(255) NULL
, [IsActive] BIT NULL
, CONSTRAINT PK_Config PRIMARY KEY CLUSTERED ( [ConfigId] )
)
GO
CREATE UNIQUE NONCLUSTERED INDEX AK_Config_ConfigName ON [core].[Config]
(
	[ConfigName] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]