CREATE TABLE [core].[Grid]
(
  [GridId] TINYINT NOT NULL IDENTITY (1, 1)
, [GridName] VARCHAR(50) NOT NULL
, CONSTRAINT PK_Grid PRIMARY KEY CLUSTERED ( [GridId] )
)
GO
CREATE UNIQUE NONCLUSTERED INDEX AK_Grid_GridName ON [core].[Grid]
(
	[GridName] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]