CREATE TABLE [core].[Location]
(
  [LocationId] SMALLINT NOT NULL IDENTITY (1, 1)
, [LocationCode] VARCHAR(20) NOT NULL
, [LocationName] VARCHAR(100) NOT NULL
, [IsActive] BIT NOT NULL
, CONSTRAINT PK_Location PRIMARY KEY CLUSTERED ( [LocationId] )
)
GO
CREATE UNIQUE NONCLUSTERED INDEX AK_Location_LocationCode ON [core].[Location]
(
	[LocationCode] ASC
)
INCLUDE ([LocationName], [IsActive])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX AK_Location_LocationName ON [core].[Location]
(
	[LocationName] ASC
)
INCLUDE ([LocationCode], [IsActive])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]