CREATE TABLE [core].[LookupEntityType]
(
  [LookupEntityTypeId] INT NOT NULL IDENTITY (1, 1)
, [LookupEntityTypeDesc] NVARCHAR(50) NULL
, [LookupEntityTypeCode] VARCHAR(10) NOT NULL
, CONSTRAINT PK_LookupEntityType PRIMARY KEY CLUSTERED ( [LookupEntityTypeId] )
)
GO
CREATE UNIQUE NONCLUSTERED INDEX AK_LookupEntityType_LookupEntityTypeCode ON [core].[LookupEntityType]
(
	[LookupEntityTypeCode] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]