CREATE TABLE [core].[Product]
(
  [ProductId] TINYINT NOT NULL
, [ProductCode] VARCHAR(20) NOT NULL
, [ProductName] VARCHAR(100) NOT NULL
, [ProductTypeId] TINYINT NOT NULL
, [UnitMeasureId] TINYINT NOT NULL
, [SizeMaxDp] TINYINT NOT NULL
, [AutoIssueWarrants] BIT NOT NULL
, [IsActive] BIT NOT NULL
, CONSTRAINT PK_Product PRIMARY KEY CLUSTERED ( [ProductId] )
, CONSTRAINT FK_Product_ProductTypeId FOREIGN KEY ( ProductTypeId ) REFERENCES core.ProductType ( ProductTypeId )
, CONSTRAINT FK_Product_UnitMeasureId FOREIGN KEY ( UnitMeasureId ) REFERENCES core.UnitMeasure ( UnitMeasureId )
)
GO
CREATE UNIQUE NONCLUSTERED INDEX AK_Product_ProductCode ON [core].[Product]
(
	[ProductCode] ASC
)
INCLUDE ([ProductName], [ProductTypeId], [IsActive])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX AK_Product_ProductName ON [core].[Product]
(
	[ProductName] ASC
)
INCLUDE ([ProductCode], [ProductTypeId], [IsActive])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]