CREATE TABLE [storage].[Store]
(
  [StoreId] SMALLINT NOT NULL IDENTITY (1, 1)
, [StorageCompanyId] SMALLINT NOT NULL
, [StoreCode] NVARCHAR(50) NOT NULL
, [StoreName] NVARCHAR(100) NOT NULL
, [LocationId] SMALLINT NOT NULL
, [IsActive] BIT NOT NULL
, CONSTRAINT PK_Store PRIMARY KEY CLUSTERED ( [StoreId] )
, CONSTRAINT FK_Store_StorageCompanyId FOREIGN KEY ( StorageCompanyId ) REFERENCES companies.Company ( CompanyId )
, CONSTRAINT FK_Store_LocationId FOREIGN KEY ( LocationId ) REFERENCES core.Location ( LocationId )
)
GO
CREATE UNIQUE NONCLUSTERED INDEX AK_Store_StoreCode ON [storage].[Store]
(
	[StoreCode] ASC
)
INCLUDE ([StorageCompanyId], [StoreName])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX AK_Store_StoreName ON [storage].[Store]
(
	[StoreName] ASC
)
INCLUDE ([StorageCompanyId], [StoreCode])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]