CREATE TABLE [inventory].[RequestType]
(
  [RequestTypeId] TINYINT NOT NULL
, [RequestTypeCode] VARCHAR(50) NOT NULL
, [RequestTypeName] VARCHAR(100) NOT NULL
, CONSTRAINT PK_RequestType PRIMARY KEY CLUSTERED ( [RequestTypeId] )
)
GO
CREATE UNIQUE NONCLUSTERED INDEX AK_RequestType_RequestTypeCode ON [inventory].[RequestType]
(
	[RequestTypeCode] ASC
)
INCLUDE ([RequestTypeName])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX AK_RequestType_RequestTypeName ON [inventory].[RequestType]
(
	[RequestTypeName] ASC
)
INCLUDE ([RequestTypeCode])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]