CREATE TABLE [dbo].[webpages_Roles]
(
  [RoleId] SMALLINT NOT NULL
, [RoleName] NVARCHAR(256) NOT NULL
, CONSTRAINT PK_webpages_Roles PRIMARY KEY CLUSTERED ( [RoleId] )
)
GO
CREATE UNIQUE NONCLUSTERED INDEX AK_webpages_Roles_RoleName ON [dbo].[webpages_Roles]
(
	[RoleName] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]